procedure InitializeComponent;
    begin
        self.textBox1 := new System.Windows.Forms.TextBox();
        self.button1 := new System.Windows.Forms.Button();
        self.button2 := new System.Windows.Forms.Button();
        self.button3 := new System.Windows.Forms.Button();
        self.button4 := new System.Windows.Forms.Button();
        self.button5 := new System.Windows.Forms.Button();
        self.button6 := new System.Windows.Forms.Button();
        self.button7 := new System.Windows.Forms.Button();
        self.button8 := new System.Windows.Forms.Button();
        self.button9 := new System.Windows.Forms.Button();
        self.button10 := new System.Windows.Forms.Button();
        self.button11 := new System.Windows.Forms.Button();
        self.button12 := new System.Windows.Forms.Button();
        self.button13 := new System.Windows.Forms.Button();
        self.button14 := new System.Windows.Forms.Button();
        self.button15 := new System.Windows.Forms.Button();
        self.button16 := new System.Windows.Forms.Button();
        self.button17 := new System.Windows.Forms.Button();
        self.button18 := new System.Windows.Forms.Button();
        self.button19 := new System.Windows.Forms.Button();
        self.button20 := new System.Windows.Forms.Button();
        self.button21 := new System.Windows.Forms.Button();
        self.button22 := new System.Windows.Forms.Button();
        self.button23 := new System.Windows.Forms.Button();
        self.button24 := new System.Windows.Forms.Button();
        self.button25 := new System.Windows.Forms.Button();
        self.button26 := new System.Windows.Forms.Button();
        self.button27 := new System.Windows.Forms.Button();
        self.button28 := new System.Windows.Forms.Button();
        self.SuspendLayout();
        // 
        // textBox1
        // 
        self.textBox1.Font := new System.Drawing.Font('Consolas', 24, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, (System.Byte(204)));
        self.textBox1.Location := new System.Drawing.Point(31, 30);
        self.textBox1.Name := 'textBox1';
        self.textBox1.ReadOnly := true;
        self.textBox1.Size := new System.Drawing.Size(286, 45);
        self.textBox1.TabIndex := 0;
        self.textBox1.TextAlign := System.Windows.Forms.HorizontalAlignment.Right;
        // 
        // button1
        // 
        self.button1.Location := new System.Drawing.Point(31, 102);
        self.button1.Name := 'button1';
        self.button1.Size := new System.Drawing.Size(50, 45);
        self.button1.TabIndex := 1;
        self.button1.Text := 'MC';
        self.button1.UseVisualStyleBackColor := true;
        // 
        // button2
        // 
        self.button2.Font := new System.Drawing.Font('Microsoft Sans Serif', 20.25, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, (System.Byte(204)));
        self.button2.Location := new System.Drawing.Point(31, 213);
        self.button2.Name := 'button2';
        self.button2.Size := new System.Drawing.Size(50, 45);
        self.button2.TabIndex := 2;
        self.button2.Text := '1';
        self.button2.UseVisualStyleBackColor := true;
        // 
        // button3
        // 
        self.button3.Font := new System.Drawing.Font('Microsoft Sans Serif', 20.25, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, (System.Byte(204)));
        self.button3.Location := new System.Drawing.Point(31, 264);
        self.button3.Name := 'button3';
        self.button3.Size := new System.Drawing.Size(50, 45);
        self.button3.TabIndex := 3;
        self.button3.Text := '4';
        self.button3.UseVisualStyleBackColor := true;
        // 
        // button4
        // 
        self.button4.Location := new System.Drawing.Point(87, 102);
        self.button4.Name := 'button4';
        self.button4.Size := new System.Drawing.Size(50, 45);
        self.button4.TabIndex := 4;
        self.button4.Text := 'MR';
        self.button4.UseVisualStyleBackColor := true;
        // 
        // button5
        // 
        self.button5.Font := new System.Drawing.Font('Microsoft Sans Serif', 20.25, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, (System.Byte(204)));
        self.button5.Location := new System.Drawing.Point(87, 213);
        self.button5.Name := 'button5';
        self.button5.Size := new System.Drawing.Size(50, 45);
        self.button5.TabIndex := 5;
        self.button5.Text := '2';
        self.button5.UseVisualStyleBackColor := true;
        // 
        // button6
        // 
        self.button6.Font := new System.Drawing.Font('Microsoft Sans Serif', 20.25, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, (System.Byte(204)));
        self.button6.Location := new System.Drawing.Point(87, 264);
        self.button6.Name := 'button6';
        self.button6.Size := new System.Drawing.Size(50, 45);
        self.button6.TabIndex := 6;
        self.button6.Text := '5';
        self.button6.UseVisualStyleBackColor := true;
        // 
        // button7
        // 
        self.button7.Location := new System.Drawing.Point(143, 102);
        self.button7.Name := 'button7';
        self.button7.Size := new System.Drawing.Size(50, 45);
        self.button7.TabIndex := 7;
        self.button7.Text := 'MS';
        self.button7.UseVisualStyleBackColor := true;
        // 
        // button8
        // 
        self.button8.Font := new System.Drawing.Font('Microsoft Sans Serif', 20.25, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, (System.Byte(204)));
        self.button8.Location := new System.Drawing.Point(143, 213);
        self.button8.Name := 'button8';
        self.button8.Size := new System.Drawing.Size(50, 45);
        self.button8.TabIndex := 8;
        self.button8.Text := '3';
        self.button8.UseVisualStyleBackColor := true;
        // 
        // button9
        // 
        self.button9.Font := new System.Drawing.Font('Microsoft Sans Serif', 20.25, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, (System.Byte(204)));
        self.button9.Location := new System.Drawing.Point(143, 264);
        self.button9.Name := 'button9';
        self.button9.Size := new System.Drawing.Size(50, 45);
        self.button9.TabIndex := 9;
        self.button9.Text := '6';
        self.button9.UseVisualStyleBackColor := true;
        // 
        // button10
        // 
        self.button10.Location := new System.Drawing.Point(211, 102);
        self.button10.Name := 'button10';
        self.button10.Size := new System.Drawing.Size(50, 45);
        self.button10.TabIndex := 10;
        self.button10.Text := 'M+';
        self.button10.UseVisualStyleBackColor := true;
        // 
        // button11
        // 
        self.button11.Font := new System.Drawing.Font('OpenSymbol', 21.75, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, (System.Byte(0)));
        self.button11.Location := new System.Drawing.Point(211, 213);
        self.button11.Name := 'button11';
        self.button11.Size := new System.Drawing.Size(50, 45);
        self.button11.TabIndex := 11;
        self.button11.Text := '/';
        self.button11.UseVisualStyleBackColor := true;
        // 
        // button12
        // 
        self.button12.Font := new System.Drawing.Font('OpenSymbol', 21.75, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, (System.Byte(0)));
        self.button12.Location := new System.Drawing.Point(211, 264);
        self.button12.Name := 'button12';
        self.button12.Size := new System.Drawing.Size(50, 45);
        self.button12.TabIndex := 12;
        self.button12.Text := '*';
        self.button12.UseVisualStyleBackColor := true;
        // 
        // button13
        // 
        self.button13.Location := new System.Drawing.Point(267, 102);
        self.button13.Name := 'button13';
        self.button13.Size := new System.Drawing.Size(50, 45);
        self.button13.TabIndex := 13;
        self.button13.Text := 'M-';
        self.button13.UseVisualStyleBackColor := true;
        // 
        // button14
        // 
        self.button14.Font := new System.Drawing.Font('OpenSymbol', 21.75, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, (System.Byte(0)));
        self.button14.Location := new System.Drawing.Point(267, 213);
        self.button14.Name := 'button14';
        self.button14.Size := new System.Drawing.Size(50, 45);
        self.button14.TabIndex := 14;
        self.button14.Text := '%';
        self.button14.UseVisualStyleBackColor := true;
        // 
        // button15
        // 
        self.button15.Font := new System.Drawing.Font('OpenSymbol', 20.25, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, (System.Byte(0)));
        self.button15.Location := new System.Drawing.Point(267, 264);
        self.button15.Name := 'button15';
        self.button15.Size := new System.Drawing.Size(50, 45);
        self.button15.TabIndex := 15;
        self.button15.Text := '1/x';
        self.button15.UseVisualStyleBackColor := true;
        // 
        // button16
        // 
        self.button16.Font := new System.Drawing.Font('Microsoft Sans Serif', 20.25, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, (System.Byte(204)));
        self.button16.Location := new System.Drawing.Point(31, 315);
        self.button16.Name := 'button16';
        self.button16.Size := new System.Drawing.Size(50, 45);
        self.button16.TabIndex := 16;
        self.button16.Text := '7';
        self.button16.UseVisualStyleBackColor := true;
        // 
        // button17
        // 
        self.button17.Font := new System.Drawing.Font('Microsoft Sans Serif', 20.25, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, (System.Byte(204)));
        self.button17.Location := new System.Drawing.Point(87, 315);
        self.button17.Name := 'button17';
        self.button17.Size := new System.Drawing.Size(50, 45);
        self.button17.TabIndex := 17;
        self.button17.Text := '8';
        self.button17.UseVisualStyleBackColor := true;
        // 
        // button18
        // 
        self.button18.Font := new System.Drawing.Font('Microsoft Sans Serif', 20.25, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, (System.Byte(204)));
        self.button18.Location := new System.Drawing.Point(143, 315);
        self.button18.Name := 'button18';
        self.button18.Size := new System.Drawing.Size(50, 45);
        self.button18.TabIndex := 18;
        self.button18.Text := '9';
        self.button18.UseVisualStyleBackColor := true;
        // 
        // button19
        // 
        self.button19.Font := new System.Drawing.Font('OpenSymbol', 21.75, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, (System.Byte(0)));
        self.button19.Location := new System.Drawing.Point(211, 315);
        self.button19.Name := 'button19';
        self.button19.Size := new System.Drawing.Size(50, 45);
        self.button19.TabIndex := 19;
        self.button19.Text := '-';
        self.button19.UseVisualStyleBackColor := true;
        // 
        // button20
        // 
        self.button20.Font := new System.Drawing.Font('Microsoft Sans Serif', 27.75, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, (System.Byte(204)));
        self.button20.Location := new System.Drawing.Point(267, 315);
        self.button20.Name := 'button20';
        self.button20.Size := new System.Drawing.Size(50, 96);
        self.button20.TabIndex := 20;
        self.button20.Text := '=';
        self.button20.UseVisualStyleBackColor := true;
        // 
        // button21
        // 
        self.button21.Font := new System.Drawing.Font('OpenSymbol', 21.75, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, (System.Byte(0)));
        self.button21.Location := new System.Drawing.Point(211, 366);
        self.button21.Name := 'button21';
        self.button21.Size := new System.Drawing.Size(50, 45);
        self.button21.TabIndex := 21;
        self.button21.Text := '+';
        self.button21.UseVisualStyleBackColor := true;
        // 
        // button22
        // 
        self.button22.Font := new System.Drawing.Font('Microsoft Sans Serif', 24, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, (System.Byte(204)));
        self.button22.Location := new System.Drawing.Point(143, 366);
        self.button22.Name := 'button22';
        self.button22.Size := new System.Drawing.Size(50, 45);
        self.button22.TabIndex := 22;
        self.button22.Text := '.';
        self.button22.UseVisualStyleBackColor := true;
        // 
        // button23
        // 
        self.button23.Font := new System.Drawing.Font('Microsoft Sans Serif', 20.25, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, (System.Byte(204)));
        self.button23.Location := new System.Drawing.Point(31, 366);
        self.button23.Name := 'button23';
        self.button23.Size := new System.Drawing.Size(106, 45);
        self.button23.TabIndex := 23;
        self.button23.Text := '0';
        self.button23.UseVisualStyleBackColor := true;
        // 
        // button24
        // 
        self.button24.Font := new System.Drawing.Font('Verdana', 21.75, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, (System.Byte(204)));
        self.button24.Location := new System.Drawing.Point(31, 153);
        self.button24.Name := 'button24';
        self.button24.Size := new System.Drawing.Size(50, 45);
        self.button24.TabIndex := 24;
        self.button24.Text := '←';
        self.button24.TextAlign := System.Drawing.ContentAlignment.TopCenter;
        self.button24.UseVisualStyleBackColor := true;
        // 
        // button25
        // 
        self.button25.Font := new System.Drawing.Font('OpenSymbol', 20.25, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, (System.Byte(0)));
        self.button25.Location := new System.Drawing.Point(87, 153);
        self.button25.Name := 'button25';
        self.button25.Size := new System.Drawing.Size(50, 45);
        self.button25.TabIndex := 25;
        self.button25.Text := 'CE';
        self.button25.UseVisualStyleBackColor := true;
        // 
        // button26
        // 
        self.button26.Font := new System.Drawing.Font('OpenSymbol', 20.25, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, (System.Byte(0)));
        self.button26.Location := new System.Drawing.Point(143, 153);
        self.button26.Name := 'button26';
        self.button26.Size := new System.Drawing.Size(50, 45);
        self.button26.TabIndex := 26;
        self.button26.Text := 'C';
        self.button26.UseVisualStyleBackColor := true;
        // 
        // button27
        // 
        self.button27.Font := new System.Drawing.Font('Microsoft Sans Serif', 21.75, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, (System.Byte(204)));
        self.button27.Location := new System.Drawing.Point(211, 153);
        self.button27.Name := 'button27';
        self.button27.Size := new System.Drawing.Size(50, 45);
        self.button27.TabIndex := 27;
        self.button27.Text := '±';
        self.button27.UseVisualStyleBackColor := true;
        // 
        // button28
        // 
        self.button28.Font := new System.Drawing.Font('OpenSymbol', 24, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, (System.Byte(0)));
        self.button28.Location := new System.Drawing.Point(267, 153);
        self.button28.Name := 'button28';
        self.button28.Size := new System.Drawing.Size(50, 45);
        self.button28.TabIndex := 28;
        self.button28.Text := '√';
        self.button28.UseVisualStyleBackColor := true;
        // 
        // Form1
        // 
        self.ClientSize := new System.Drawing.Size(348, 480);
        self.Controls.Add(self.button28);
        self.Controls.Add(self.button27);
        self.Controls.Add(self.button26);
        self.Controls.Add(self.button25);
        self.Controls.Add(self.button24);
        self.Controls.Add(self.button23);
        self.Controls.Add(self.button22);
        self.Controls.Add(self.button21);
        self.Controls.Add(self.button20);
        self.Controls.Add(self.button19);
        self.Controls.Add(self.button18);
        self.Controls.Add(self.button17);
        self.Controls.Add(self.button16);
        self.Controls.Add(self.button15);
        self.Controls.Add(self.button14);
        self.Controls.Add(self.button13);
        self.Controls.Add(self.button12);
        self.Controls.Add(self.button11);
        self.Controls.Add(self.button10);
        self.Controls.Add(self.button9);
        self.Controls.Add(self.button8);
        self.Controls.Add(self.button7);
        self.Controls.Add(self.button6);
        self.Controls.Add(self.button5);
        self.Controls.Add(self.button4);
        self.Controls.Add(self.button3);
        self.Controls.Add(self.button2);
        self.Controls.Add(self.button1);
        self.Controls.Add(self.textBox1);
        self.MaximizeBox := false;
        self.MaximumSize := new System.Drawing.Size(364, 519);
        self.MinimizeBox := false;
        self.MinimumSize := new System.Drawing.Size(364, 519);
        self.Name := 'Form1';
        self.Text := 'Form1';
        self.ResumeLayout(false);
        self.PerformLayout();
    end;
